name: test
on:
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --timeout=10m
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Get dependencies
        run: go mod download

      - name: Check mod
        run: make check-mod

      - name: Check doc
        run: make check-docs

      - name: Test
        run: make test

# todo: add acceptance tests
